### PR TITLE
internal/docstore/dynamodocstore: use httpreplay for tests

### LINKED ISSUE #1971: docstore/dynamodocstore: switch to use httpreplay
`docstore/dynamodocstore` is the only remaining user of go-vcr for AWS. I'm trying to port it to use `NewAWSSession2` (which uses httpreplay) but am running into issues, like:

```
    --- FAIL: TestConformance/Query (1.58s)
        setup.go:77: Recording into golden file testdata/TestConformance/Query.replay
        --- FAIL: TestConformance/Query/All (0.08s)
            drivertest.go:904:   []*drivertest.HighScore(Inverse(cmpopts.SortSlices, []*drivertest.HighScore{
                - 	s"Days Gone|mia=99@04/26",
                - 	s"Days Gone|steph=24@04/25",
                  	&{Game: "Praise All Monsters", Player: "andy", Score: 81, Time: s"2019-02-01 00:00:00 +0000 UTC"},
                  	&{Game: "Praise All Monsters", Player: "fran", Score: 33, Time: s"2019-03-19 00:00:00 +0000 UTC"},
                  	... // 6 identical elements
                  }))
          
```

Also there seems to be a cool-off of 10 minutes on running against the AWS dynamo store, otherwise I keep getting `IdempotentParameterMismatchException`

@shantuo can you please port this?

Related to #770

### PR DESCRIPTION
**Pull request by shantuo**
Fixes #1971
Updates #770 

1. Run `cleanupTable` before query tests.
1. Use the record time stamp as the initial state of the recorder.

### CODE REVIEW

File: internal/testing/setup/setup.go [hunk 1]
```diff
@@ -100,15 +101,19 @@ func awsSession(region string, client *http.Client) (*session.Session, error) {
...
 	path := filepath.Join("testdata", t.Name()+".replay")
 	if *Record {
 		t.Logf("Recording into golden file %s", path)
 		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
 			t.Fatal(err)
 		}
-		rec, err := httpreplay.NewRecorder(path, nil)
+		state := time.Now()
+		b, _ := state.MarshalBinary()
+		rec, err := httpreplay.NewRecorder(path, b)
```
Comment (jba) [inline internal/testing/setup/setup.go]: Move the error check on line 118 above the call to rf.

File: internal/testing/setup/setup.go [hunk 2]
```diff
@@ -100,15 +101,19 @@ func awsSession(region string, client *http.Client) (*session.Session, error) {
 // from files. rf is a modifier function that will be invoked with the address
 // of the httpreplay.Recorder object used to obtain the client; this function
 // can mutate the recorder to add provider-specific header filters, for example.
-func NewRecordReplayClient(ctx context.Context, t *testing.T, rf func(r *httpreplay.Recorder), opts ...option.ClientOption) (c *http.Client, cleanup func()) {
+// An initial state is returned for tests that need a state to have
+// deterministic results.
+func NewRecordReplayClient(ctx context.Context, t *testing.T, rf func(r *httpreplay.Recorder), opts ...option.ClientOption) (*http.Client, func(), int64) {
```
Comment (jba) [inline internal/testing/setup/setup.go]: Add back the return-value names. They were useful documentation.

File: internal/testing/setup/setup.go [hunk 3]
```diff
@@ -117,13 +122,13 @@ func NewRecordReplayClient(ctx context.Context, t *testing.T, rf func(r *httprep
...
 		}
-		cleanup = func() {
+		cleanup := func() {
 			if err := rec.Close(); err != nil {
 				t.Fatal(err)
 			}
 		}
 
-		return client, cleanup
+		return client, cleanup, state.Unix()
```
Comment (jba) [inline internal/testing/setup/setup.go]: On second thought, UnixNano is probably a better choice. Just in case someone tries to use the state twice in the same second.

File: internal/testing/setup/setup.go [hunk 4]
```diff
@@ -134,13 +139,16 @@ func NewRecordReplayClient(ctx context.Context, t *testing.T, rf func(r *httprep
...
+	if err := recState.UnmarshalBinary(rep.Initial()); err != nil {
+		t.Fatal(err)
+	}
+	return client, func() { rep.Close() }, recState.Unix()
 }
 
 // NewAWSSession2 is like NewAWSSession, but it uses a different record/replay proxy.
-func NewAWSSession2(ctx context.Context, t *testing.T, region string) (sess *session.Session, rt http.RoundTripper, cleanup func()) {
-	client, cleanup := NewRecordReplayClient(ctx, t, func(r *httpreplay.Recorder) {
+func NewAWSSession2(ctx context.Context, t *testing.T, region string) (*session.Session, http.RoundTripper, func(), int64) {
```
Comment (jba) [inline internal/testing/setup/setup.go]: Add back return-value names.

File: internal/testing/setup/setup.go [hunk 5]
```diff
@@ -100,15 +101,19 @@ func awsSession(region string, client *http.Client) (*session.Session, error) {
 // from files. rf is a modifier function that will be invoked with the address
 // of the httpreplay.Recorder object used to obtain the client; this function
 // can mutate the recorder to add provider-specific header filters, for example.
-func NewRecordReplayClient(ctx context.Context, t *testing.T, rf func(r *httpreplay.Recorder), opts ...option.ClientOption) (c *http.Client, cleanup func()) {
+// An initial state is returned for tests that need a state to have
```
Comment (eliben) [inline internal/testing/setup/setup.go]: I'd add more about the semantics of this state in this comment, it's not very clear. Also add the same for NewAWSSession2

Comment (shantuo) [reply internal/testing/setup/setup.go]: Done.

File: internal/testing/setup/setup.go (hunk 2 above)
Comment (shantuo) [reply internal/testing/setup/setup.go]: Done.

File: internal/testing/setup/setup.go (hunk 1 above)
Comment (shantuo) [reply internal/testing/setup/setup.go]: Done.

File: internal/testing/setup/setup.go (hunk 4 above)
Comment (shantuo) [reply internal/testing/setup/setup.go]: Done.

File: internal/testing/setup/setup.go (hunk 3 above)
Comment (shantuo) [reply internal/testing/setup/setup.go]: Done.
