### PR TITLE
pubsub: ensure that goroutines finish before test ends

### LINKED ISSUE #810: pubsub: panic in TestConcurrentReceivesGetAllTheMessages
Travis reported this:

```
panic: Fail in goroutine after TestConcurrentReceivesGetAllTheMessages has completed
goroutine 2168 [running]:
testing.(*common).Fail(0xc000575a00)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:546 +0x1c6
testing.(*common).FailNow(0xc000575a00)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:568 +0x39
testing.(*common).Fatal(0xc000575a00, 0xc000589f88, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:628 +0x7d
github.com/google/go-cloud/internal/pubsub_test.TestConcurrentReceivesGetAllTheMessages.func1(0xc0003e7c20, 0x175d540, 0xc000572a00, 0xc000575a00, 0xc0000ad5d8, 0xc00055bf50, 0xc0000ad5f0)
	/home/travis/gopath/src/github.com/google/go-cloud/internal/pubsub/pubsub_test.go:152 +0x258
created by github.com/google/go-cloud/internal/pubsub_test.TestConcurrentReceivesGetAllTheMessages
```

### PR DESCRIPTION
**Pull request by ijt**
Fixes #810

### CODE REVIEW

File: internal/pubsub/pubsub_test.go [hunk 1]
```diff
@@ -173,8 +173,15 @@ func TestConcurrentReceivesGetAllTheMessages(t *testing.T) {
 	}
 
 	// Wait for all the goroutines to finish processing all the messages.
-	wg.Wait()
+	for {
+		mu.Lock()
+		if len(receivedMsgs) == howManyToSend {
+			break
```
Comment (jba) [inline internal/pubsub/pubsub_test.go]: If you hit this line, mu will still be locked.

I like:
```
mu.Lock()
r := len(receivedMsgs)
mu.Unlock()
if r == ...
```

Comment (ijt) [reply internal/pubsub/pubsub_test.go]: Done.

**Comment by ijt** [comment]
PTAL
