### PR TITLE
internal/gocdk: consolidate some helpers && verify project root dir

### LINKED ISSUE #2210: internal/cmd/gocdk: demo add proceeds even outside a project directory
### Describe the bug

The `gocdk demo add` command unconditionally adds a file to the current directory, regardless of whether it is in a project or not.

/cc @vangent 

### To Reproduce

```
cd random/dir
gocdk demo add blob
```

creates a demo_blob.go file.

## Expected behavior

An error is returned: the file should only be inserted at the root of the current module, of which we are not in one.

### PR DESCRIPTION
**Pull request by vangent**
Fixes #2210.

I started fixing #2210 (about "demo add" happening even when you're not in the project directory) and kind of went down a rabbit hole:

* I ended up modifying `findModuleRoot` to do the check for whether we're in a Go CDK directory, since we pretty much want this everywhere. I also renamed it to `ModuleRoot` on `processContext` since we always call it with `pctx.workdir`.

* I also renamed `findBiomeDir()` to `biomeDir()` and added `biomeRootDir()`. The `find` seems unnecessary since it's just constructing the path, not finding anything.

* I got rid of the `newTestModule` helper in favor of using `newTestProject`, which uses `gocdk init` to create a Go CDK project. This simplified a few tests where we were having to create `biomes` files etc. manually. In particular, `newTestBiome` is no longer needed.

* Fixed a bug in `biome add` where an error wasn't being returned.

* Simplified list of available demos; we just need the demo name, everything else can be computed.

### CODE REVIEW

File: internal/cmd/gocdk/biome.go [hunk 1]
```diff
@@ -36,16 +36,21 @@ type biomeConfig struct {
 	Launcher     *string `json:"launcher,omitempty"`
 }
 
-// findBiomeDir returns the path to the named biome.
-func findBiomeDir(moduleRoot, name string) string {
-	return filepath.Join(moduleRoot, "biomes", name)
+// biomeRootDir returns the path to the biomes directory.
+func biomeRootDir(moduleRoot string) string {
```
Comment (clausti) [inline internal/cmd/gocdk/biome.go]: The root directory is named `biomes` rather than `biome`, should we make that match here?

File: internal/cmd/gocdk/demo.go [hunk 2]
```diff
@@ -89,52 +67,52 @@ func registerDemoCmd(ctx context.Context, pctx *processContext, rootCmd *cobra.C
...
 // instantiateDemo does all of the work required to add a demo of a
 // portable API to the user's project.
 // TODO(rvangent): It currently copies a single source code file. It should
 // additionally iterate over existing biomes, adding a config entry and possibly
 // Terraform files.
-func instantiateDemo(pctx *processContext, demo *demoInfo, force bool) error {
+func instantiateDemo(pctx *processContext, moduleRoot, demo string, force bool) error {
 	logger := log.New(pctx.stderr, "gocdk: ", log.Ldate|log.Ltime)
-	logger.Printf("Adding %q...", demo.name)
+	logger.Printf("Adding %q...", demo)
```
Comment (clausti) [inline internal/cmd/gocdk/demo.go]: should this be using the `pctx` logger?

File: internal/cmd/gocdk/biome.go (hunk 1 above)
Comment (vangent) [reply internal/cmd/gocdk/biome.go]: Sure, done.

File: internal/cmd/gocdk/demo.go (hunk 2 above)
Comment (vangent) [reply internal/cmd/gocdk/demo.go]: Yes, but that is not checked in yet. I will resolve conflicts like this before submitting depending on the submit order.
