### PR TITLE
secrets/awskms: support ARNs in URLs by allowing empty Host

### LINKED ISSUE #2808: secrets/awskms: AWS KMS keys cannot be specified by ARN
### Describe the bug

While AWS allows referencing KMS keys by the ARN of the key or alias, doing so via go-cloud is not possible. This seems to be because go-cloud attempts to [parse the ARN as a URL](https://github.com/google/go-cloud/blob/8ac135d7ab6bf0f1787c7d21bc3b4a2613478b16/internal/openurl/openurl.go#L57), which isn't possible, since ARNs contain multiple colons and are not URLs.

### To Reproduce

```go
package main

import (
	"context"
	"fmt"

	"gocloud.dev/secrets"
	_ "gocloud.dev/secrets/awskms"
)

func tryUrl(s string) {
	ctx := context.Background()
	plaintext := []byte("test plaintext")

	keeper, err := secrets.OpenKeeper(ctx, s)
	if err != nil {
		fmt.Println("ERR opening:", s, err)
		return
	}

	cipherText, err := keeper.Encrypt(ctx, plaintext)
	if err != nil {
		fmt.Println("ERR encrypting:", err)
		return
	}

	fmt.Println("OK", s, cipherText)
}

func main() {
	tryUrl("awskms://alias/gocloud-test?region=us-east-1")
	tryUrl("awskms://arn:aws:kms:us-east-1:932528106278:alias/gocloud-test?region=us-east-1")
	tryUrl("awskms://8be0dcc5-da0a-4164-a99f-649015e344b5?region=us-east-1")
	tryUrl("awskms://arn:aws:kms:us-east-1:932528106278:key/8be0dcc5-da0a-4164-a99f-649015e344b5?region=us-east-1")
}
```

This results in:
```
OK awskms://alias/gocloud-test?region=us-east-1 [1 2 2 0 120 150 216 50 135 207 212 250 237 163 12 13 103 103 106 174 177 92 164 114 115 224 59 81 182 174 16 37 167 96 79 20 27 1 122 195 222 74 101 234 120 27 137 230 113 255 130 42 3 32 0 0 0 108 48 106 6 9 42 134 72 134 247 13 1 7 6 160 93 48 91 2 1 0 48 86 6 9 42 134 72 134 247 13 1 7 1 48 30 6 9 96 134 72 1 101 3 4 1 46 48 17 4 12 120 124 56 232 248 64 106 223 86 69 51 38 2 1 16 128 41 252 100 172 48 214 33 13 118 53 198 167 155 31 13 8 10 198 4 49 202 223 188 4 127 31 33 252 2 166 249 52 159 184 130 197 140 68 125 155 9 161]
ERR opening: awskms://arn:aws:kms:us-east-1:932528106278:alias/gocloud-test?region=us-east-1 open secrets.Keeper: parse "awskms://arn:aws:kms:us-east-1:932528106278:alias/gocloud-test?region=us-east-1": invalid port ":alias" after host
OK awskms://8be0dcc5-da0a-4164-a99f-649015e344b5?region=us-east-1 [1 2 2 0 120 150 216 50 135 207 212 250 237 163 12 13 103 103 106 174 177 92 164 114 115 224 59 81 182 174 16 37 167 96 79 20 27 1 158 222 101 116 57 224 186 233 152 71 99 32 116 99 31 165 0 0 0 108 48 106 6 9 42 134 72 134 247 13 1 7 6 160 93 48 91 2 1 0 48 86 6 9 42 134 72 134 247 13 1 7 1 48 30 6 9 96 134 72 1 101 3 4 1 46 48 17 4 12 52 34 218 108 172 44 21 80 184 133 34 189 2 1 16 128 41 212 32 11 1 212 152 61 182 224 77 82 39 208 137 94 112 117 141 107 14 31 125 132 218 169 133 62 177 143 136 152 194 239 203 107 8 154 226 254 151 92]
ERR opening: awskms://arn:aws:kms:us-east-1:932528106278:key/8be0dcc5-da0a-4164-a99f-649015e344b5?region=us-east-1 open secrets.Keeper: parse "awskms://arn:aws:kms:us-east-1:932528106278:key/8be0dcc5-da0a-4164-a99f-649015e344b5?region=us-east-1": invalid port ":key" after host
```

## Expected behavior

All four attempts should produce a ciphertext.

### Version

v0.19.0, but I believe it's present in all versions.

### PR DESCRIPTION
**Pull request by vangent**
For example, "awskms:///my:arn" now works.

Fixes #2808

### CODE REVIEW

**Comment by eliben** [comment]
> For example, "awskms:///my:arn" now works.
> 
> Fixes #2028

You mean #2808?

File: secrets/awskms/kms.go [hunk 1]
```diff
@@ -96,12 +97,13 @@ func (o *lazySessionOpener) OpenKeeperURL(ctx context.Context, u *url.URL) (*sec
...
 const Scheme = "awskms"
 
-// URLOpener opens AWS KMS URLs like "awskms://keyID".
+// URLOpener opens AWS KMS URLs like "awskms://keyID" or "awskms:///keyID".
 //
 // The URL Host + Path are used as the key ID, which can be in the form of an
 // Amazon Resource Name (ARN), alias name, or alias ARN. See
 // https://docs.aws.amazon.com/kms/latest/developerguide/viewing-keys.html#find-cmk-id-arn
-// for more details.
+// for more details. Note that ARNs may contain ":" characters, which cannot be
```
Comment (eliben) [inline secrets/awskms/kms.go:105]: This may need more clarity in what the exact case we're handling? The issue reporting this had two //s before the ARN

Comment (vangent) [reply secrets/awskms/kms.go:105]: Before this PR, we concatenated the Host and Path to form the KeyID. ARNs did not work correctly because they have ":" characters, which can't be escaped in the Host, and the parsing expects to be followed by a port number. So, the URLs in the bug report don't parse.

You could always leave the Host empty (e.g., "awskms:///foo:bar"), even before this PR, but since Paths start with a "/", you'd end up with a KeyID like "/foo:bar", which wouldn't work.

In this PR, I'm checking for that case and dropping the leading "/" if the Host is empty. So the user who filed the bug will have to change their URLs to have "awskms:///" instead of "awskms://" and then it will work.

This docstring is pointing out that if your ARN has ":", you need to use the 3-slash form.

**Comment by vangent** [comment]
> > For example, "awskms:///my:arn" now works.
> > Fixes #2028
> 
> You mean #2808?

Oops, yes.
