### PR TITLE
pubsub/tests: simplify TestConcurrentReceivesGetAllTheMessages

### LINKED ISSUE #829: pubsub: TestConcurrentReceivesGetAllTheMessages fails intermittently
Found on Travis:

```
ok  	github.com/google/go-cloud/internal/batcher	3.904s	coverage: 1.0% of statements in ./...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa6039f]
goroutine 1400 [running]:
github.com/google/go-cloud/internal/pubsub_test.TestConcurrentReceivesGetAllTheMessages.func1(0xc0003ac5a0, 0xc000317770, 0x1779180, 0xc00053e5c0, 0xc000309000, 0xc0003ac5b0, 0xc0003af770)
	C:/Users/travis/gopath/src/github.com/google/go-cloud/internal/pubsub/pubsub_test.go:157 +0x8f
created by github.com/google/go-cloud/internal/pubsub_test.TestConcurrentReceivesGetAllTheMessages
	C:/Users/travis/gopath/src/github.com/google/go-cloud/internal/pubsub/pubsub_test.go:146 +0x448
FAIL	github.com/google/go-cloud/internal/pubsub	2.199s
```

### PR DESCRIPTION
**Pull request by vangent**
Instead of keeping a map with counter (string->int) for each unique message key, keep a set (string->bool). The counter would never be anything other than 0 or 1; the test would hang if it failed to deliver them all.

Also, just verify the expected keys are in the set at the end instead of creating a second set containing them.

Fixes #829.

### CODE REVIEW

File: internal/pubsub/pubsub_test.go [hunk 1]
```diff
@@ -185,17 +183,10 @@ func TestConcurrentReceivesGetAllTheMessages(t *testing.T) {
...
-	if sum != howManyToSend {
-		t.Errorf("received %d messages, want %d", sum, howManyToSend)
-	}
-	for k, v := range sentMsgs {
-		v2 := receivedMsgs[k]
-		if v2 != v {
-			t.Errorf("got %d for %q, want %d", v2, k, v)
+	for i := 0; i < howManyToSend; i++ {
+		key := fmt.Sprintf("message #%d", i)
+		if _, found := receivedMsgs[key]; !found {
```
Comment (jba) [inline internal/pubsub/pubsub_test.go]: In this case, I think this is equivalent to
```
if !receivedMsgs[key] {
```

Comment (vangent) [reply internal/pubsub/pubsub_test.go]: Yup; done.
