### PR TITLE
pubsub/azurepubsub: fix broken test for Subscription Error.As

### LINKED ISSUE #1326: pubsub/azure: tests are failing with -record
```
google/go-cloud/pubsub/azurepubsub$ go test -v -record --run TestConformance/TestAs/asb
=== RUN   TestConformance
=== RUN   TestConformance/TestAs
=== RUN   TestConformance/TestAs/asb
--- FAIL: TestConformance (10.54s)
    --- FAIL: TestConformance/TestAs (10.54s)
        --- FAIL: TestConformance/TestAs/asb (10.54s)
            drivertest.go:505: failed to convert pubsub (code=Unknown): azurepubsub: no such subscription nonexistent-subscription (common.Retryable) to a common.Retryable
FAIL
exit status 1
FAIL	gocloud.dev/pubsub/azurepubsub	10.671s
```

### PR DESCRIPTION
**Pull request by vangent**
Fixes #1326.

### CODE REVIEW

File: pubsub/azurepubsub/azurepubsub_test.go [hunk 1]
```diff
@@ -178,16 +178,14 @@ func (sbAsTest) SubscriptionCheck(sub *pubsub.Subscription) error {
...
 	}
 	return nil
 }
 
 func (sbAsTest) SubscriptionErrorCheck(s *pubsub.Subscription, err error) error {
-	var sbError common.Retryable
-	if !s.ErrorAs(err, &sbError) {
-		return fmt.Errorf("failed to convert %v (%T) to a common.Retryable", err, sbError)
-	}
+	// We generate our own error for non-existent subscription, so there's no
```
Comment (ijt) [inline pubsub/azurepubsub/azurepubsub_test.go]: Is this the actual fix?

Comment (vangent) [reply pubsub/azurepubsub/azurepubsub_test.go]: Yes.
