### PR TITLE
filevar: Rework filevar to simplify it and avoid race conditions.

### LINKED ISSUE #334: filevar: tests are flaky
Travis run timed out: https://travis-ci.com/google/go-cloud/jobs/140213735

...
?   	github.com/google/go-cloud/runtimevar/driver	[no test files]
SIGQUIT: quit
PC=0x109d480 m=0 sigcode=0
goroutine 5 [syscall]:
syscall.Syscall6(0x16b, 0x8, 0x0, 0x0, 0xc420048e88, 0xa, 0x13c8600, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.10.3.darwin.amd64/src/syscall/asm_darwin_amd64.s:41 +0x5 fp=0xc420048ab0 sp=0xc420048aa8 pc=0x109d455
golang.org/x/sys/unix.kevent(0x8, 0x0, 0x0, 0xc420048e88, 0xa, 0x13c8600, 0x0, 0x0, 0x0)
	/Users/travis/gopath/pkg/mod/golang.org/x/sys@v0.0.0-20180329131831-378d26f46672/unix/zsyscall_darwin_amd64.go:207 +0xbf fp=0xc420048b48 sp=0xc420048ab0 pc=0x11ee87f
golang.org/x/sys/unix.Kevent(0x8, 0x0, 0x0, 0x0, 0xc420048e88, 0xa, 0xa, 0x13c8600, 0xc420048c28, 0x102d77a, ...)
	/Users/travis/gopath/pkg/mod/golang.org/x/sys@v0.0.0-20180329131831-378d26f46672/unix/syscall_bsd.go:460 +0x8d fp=0xc420048bb8 sp=0xc420048b48 pc=0x11ee08d
github.com/fsnotify/fsnotify.read(0x8, 0xc420048e88, 0xa, 0xa, 0x13c8600, 0xc420048e88, 0x0, 0xa, 0x0, 0x0)
	/Users/travis/gopath/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/kqueue.go:511 +0x85 fp=0xc420048c38 sp=0xc420048bb8 pc=0x11f2fb5
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc42006a060)
	/Users/travis/gopath/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/kqueue.go:274 +0x81c fp=0xc420048fd8 sp=0xc420048c38 pc=0x11f1dbc
runtime.goexit()
	/Users/travis/.gimme/versions/go1.10.3.darwin.amd64/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420048fe0 sp=0xc420048fd8 pc=0x1089d51
created by github.com/fsnotify/fsnotify.NewWatcher
	/Users/travis/gopath/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/kqueue.go:62 +0x332
goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200c6000, 0x1281f72, 0x26, 0x12859f0, 0xc42005dc01)
	/Users/travis/.gimme/versions/go1.10.3.darwin.amd64/src/testing/testing.go:825 +0x597
testing.runTests.func1(0xc4200c6000)
	/Users/travis/.gimme/versions/go1.10.3.darwin.amd64/src/testing/testing.go:1063 +0xa5
testing.tRunner(0xc4200c6000, 0xc42005ddb0)
	/Users/travis/.gimme/versions/go1.10.3.darwin.amd64/src/testing/testing.go:777 +0x16e
testing.runTests(0xc42009c720, 0x13a8da0, 0x8, 0x8, 0xc4200c2000)
	/Users/travis/.gimme/versions/go1.10.3.darwin.amd64/src/testing/testing.go:1061 +0x4e2
testing.(*M).Run(0xc4200c2000, 0x0)
	/Users/travis/.gimme/versions/go1.10.3.darwin.amd64/src/testing/testing.go:978 +0x2ce
main.main()
	_testmain.go:58 +0x22b
goroutine 12 [select]:
github.com/google/go-cloud/runtimevar/filevar.(*watcher).WatchVariable(0xc42006a3c0, 0x129f380, 0xc42008e048, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/google/go-cloud/runtimevar/filevar/filevar.go:153 +0x8b2
github.com/google/go-cloud/runtimevar.(*Variable).Watch(0xc420026190, 0x129f380, 0xc42008e048, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/google/go-cloud/runtimevar/runtimevar.go:71 +0xbf
github.com/google/go-cloud/runtimevar/filevar.TestReturnsUpdatedSnapshotConcurrently(0xc4200d23c0)
	/Users/travis/gopath/src/github.com/google/go-cloud/runtimevar/filevar/filevar_test.go:205 +0x235
testing.tRunner(0xc4200d23c0, 0x12859f0)
	/Users/travis/.gimme/versions/go1.10.3.darwin.amd64/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/Users/travis/.gimme/versions/go1.10.3.darwin.amd64/src/testing/testing.go:824 +0x565
goroutine 13 [syscall]:
syscall.Syscall6(0x16b, 0xd, 0x0, 0x0, 0xc420110e88, 0xa, 0x13c8600, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.10.3.darwin.amd64/src/syscall/asm_darwin_amd64.s:41 +0x5
golang.org/x/sys/unix.kevent(0xd, 0x0, 0x0, 0xc420110e88, 0xa, 0x13c8600, 0x0, 0x0, 0x0)
	/Users/travis/gopath/pkg/mod/golang.org/x/sys@v0.0.0-20180329131831-378d26f46672/unix/zsyscall_darwin_amd64.go:207 +0xbf
golang.org/x/sys/unix.Kevent(0xd, 0x0, 0x0, 0x0, 0xc420110e88, 0xa, 0xa, 0x13c8600, 0xc420110c28, 0x102d77a, ...)
	/Users/travis/gopath/pkg/mod/golang.org/x/sys@v0.0.0-20180329131831-378d26f46672/unix/syscall_bsd.go:460 +0x8d
github.com/fsnotify/fsnotify.read(0xd, 0xc420110e88, 0xa, 0xa, 0x13c8600, 0xc420110e88, 0x0, 0xa, 0x0, 0x0)
	/Users/travis/gopath/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/kqueue.go:511 +0x85
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc42006a360)
	/Users/travis/gopath/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/kqueue.go:274 +0x81c
created by github.com/fsnotify/fsnotify.NewWatcher
	/Users/travis/gopath/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/kqueue.go:62 +0x332
rax    0x4
rbx    0x0
rcx    0xc420048aa8
rdx    0x0
rdi    0x8
rsi    0x0
rbp    0xc420048b38
rsp    0xc420048aa8
r8     0xa
r9     0x13c8600
r10    0xc420048e88
r11    0x202
r12    0xc420048aa0
r13    0x13ac9e0
r14    0xc420001500
r15    0xa
rip    0x109d480
rflags 0x203
cs     0x7
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/google/go-cloud/runtimevar/filevar	600.088s

### PR DESCRIPTION
**Pull request by vangent**
Fixes #334.

### CODE REVIEW

File: runtimevar/filevar/filevar.go [hunk 1]
```diff
@@ -111,68 +111,58 @@ func (w *watcher) WatchVariable(ctx context.Context) (driver.Variable, error) {
...
 				t.Stop()
 				return zeroVar, ctx.Err()
 			}
-
-		case noChangeState:
-			wait = false
+			continue
 		}
-	}
-
```
Comment (vangent) [inline runtimevar/filevar/filevar.go]: This is where the race was before; if you insert a Sleep(1 * time.Second) here some of the tests hang forever. It happens if the change occurs after the processFile above, but before the notifier.Add happens, so the notifier never gets an event.

File: runtimevar/filevar/filevar.go [hunk 2]
```diff
@@ -186,67 +176,35 @@ type WatchOptions struct {
 	WaitTime time.Duration
 }
 
-// watchState defines the different states during a watch for the Watch call to process.
```
Comment (vangent) [inline runtimevar/filevar/filevar.go]: I think the implementation is simpler without all of this, agree?

File: runtimevar/filevar/filevar.go [hunk 3]
```diff
@@ -111,68 +111,58 @@ func (w *watcher) WatchVariable(ctx context.Context) (driver.Variable, error) {
...
-	}
-
-	// Start watching over the file and wait for events/errors.
-	if err := w.notifier.Add(w.file); err != nil {
-		if os.IsNotExist(err) {
-			// File got deleted in between initial check above and adding a watch.
-			w.isDeleted = true
-			w.updateTime = time.Now().UTC()
+		// If file wasn't deleted, no reason for notifier to have failed.
+		if notifierErr != nil {
```
Comment (vangent) [inline runtimevar/filevar/filevar.go]: Note: here we could retry the notifier.Add instead of returning the error, but I don't think that's necessary. Agree?

File: runtimevar/filevar/filevar_test.go [hunk 4]
```diff
@@ -189,12 +189,7 @@ func TestReturnsUpdatedSnapshotConcurrently(t *testing.T) {
 
 	const content = `{"hello": "cloud"}`
 	// Update the file in a separate goroutine.
-	written := make(chan struct{})
```
Comment (vangent) [inline runtimevar/filevar/filevar_test.go]: I couldn't see why these channels were necessary....?

File: runtimevar/filevar/filevar.go (hunk 3 above)
Comment (shantuo) [reply runtimevar/filevar/filevar.go]: This is the case when the file didn't exist before. I don't think it will reach here no matter it is created (var returned), remains deleted (retry), or ctx is canceled (zeroVar returned). Do I miss anything? Is there a test case that shows what this check is used for?

File: runtimevar/filevar/filevar.go [hunk 5]
```diff
@@ -111,68 +111,60 @@ func (w *watcher) WatchVariable(ctx context.Context) (driver.Variable, error) {
...
-			return zeroVar, sd.err
+	// Start watching over the file and wait for events/errors.
+	// We'll get a notifierErr if the file doesn't currently exist.
+	// Also, note that we may never use the notifier if there's already
+	// a change to the file. We must create it now before checking to
+	// avoid race conditions.
+	notifierErr := w.notifier.Add(w.file)
+	if notifierErr == nil {
+		defer func() {
+			_ = w.notifier.Remove(w.file)
```
[the remark this answers is not in the document]
Comment (vangent) [reply runtimevar/filevar/filevar.go]: The linter Travis uses objects to that.

File: runtimevar/filevar/filevar.go (hunk 3 above)
Comment (vangent) [reply runtimevar/filevar/filevar.go]: I agree that it shouldn't get here, and I can't easily write a test that does. However, it's possible that notifier.Add fails for some reason other than "file doesn't exist", and I think it's preferable to return that error here than to go into the select{}, which will hang forever.

File: runtimevar/filevar/filevar.go [hunk 6]
```diff
@@ -186,67 +178,35 @@ type WatchOptions struct {
...
-	err      error            // Error object for hasErrorState.
-}
-
-// processFile reads the file and determines the watchState. Depending on the watchState, it may
-// update the watcher's fields bytes, isDeleted and updateTime.
-func (w *watcher) processFile() stateData {
+// processFile reads the file.
+// * If nothing has changed, it returns nil.
+// * If something has changed, it updates the watcher's bytes, isDeleted,
+//   and updateTIme fields.
```
[the remark this answers is not in the document]
Comment (vangent) [reply runtimevar/filevar/filevar.go]: Done.

**Comment by vangent** [comment]
PTAL.

File: runtimevar/filevar/filevar.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (shantuo) [reply runtimevar/filevar/filevar.go]: Ah, didn't realize that.

File: runtimevar/filevar/filevar.go (hunk 3 above)
Comment (shantuo) [reply runtimevar/filevar/filevar.go]: Yeah let's leave it here.
